name:          Code Guide by Miguel Borges
description:   Standards for developing flexible, durable, and sustainable HTML and CSS.
url:           http://www.miguelborges.com

markdown:      rdiscount
permalink:     pretty
pygments:      true
